### ISSUE TITLE
beam modification

### ISSUE THREAD

**Issue by smribet** [abTEM/abTEM#86] opened 2022-08-10 15:56 UTC
Hi Jacob, 

I've been working with Colin Ophus on 4D-STEM simulations in abTEM with a modified probe.  We spoke to @TomaSusi about our work at M&M and would be excited to contribute phase and amplitude plates to abTEM. We would be interested in adding some of the more common probes (vortex, volta, zernike, bullseye, etc.) as well as a completely tunable option. What do you think?

The way we’ve been modifying the probe so far is by changing the `CTF` before it is passed into the `Probe,` but this doesn’t seem like the best solution.  One possibility would be to expand aperture.py for a class of plates that could be added to the `Probe` similar to the `CTF`. Where would you suggest adding this feature? 

Thanks, 
Stephanie

**Comment by TomaSusi** [comment] 2022-08-10 17:27
Thanks for opening the issue! @jacobjma is on holiday this week but we'll be sure to discuss this when he's back :)

**Comment by smribet** [comment] 2022-08-10 18:40
Enjoy the vacation! Look forward to discussing in the future

**Comment by jacobjma** [comment] 2022-08-16 17:44
Hi, I love that you want to contribute to abTEM! I think you should add your contribution to the dask branch, which should make this very easy. I will give you some detailed instructions tomorrow 👍.

**Comment by jacobjma** [comment] 2022-08-22 12:49
As I said I think it is better to contribute your code to the `abtem-dask` branch, otherwise your implementation would have to be completely rewritten in the merge.

It took a little longer to reply;  as I needed to make a few changes to make this as easy as possible. Now, in the `abtem-dask` branch you can add a new aperture type object, which is completely self-contained, but fully works within *abTEM*. Hence, you don't even need to touch the source. However, your custom aperture object has to fulfill some requirements to make it work.

Your aperture object should inherit from `AbstractAperture`, which requires the argument `energy` and `semiangle_cutoff`. This ensures that all apertures can calculate "their" Nyquist sampling.

You need to expose a property for every additional argument, e.g. below we have a `num_spokes` argument which also is a property. You need to have a metadata property, which will add metadata to the wave function, this can just be left as an empty dictionary. 

Finally, you need to implement the main method `evaluate_with_alpha_and_phi` which; based on a 2d grid of radial angles (`alpha`) and azimuthal angles(`phi`) (both in radians), will calculate the array which will be multiplied with the Fourier space wave function.

This sounds a little complicated, but I think the example below shows that it is pretty easy. We create a new aperture object called `MyAperture`, with an unusual shape as shown in the image below.

```
from typing import Union

import numpy as np

from abtem.core.backend import get_array_module
from abtem.waves.transfer import BaseAperture


class MyAperture(BaseAperture):

    def __init__(self, num_spokes: float, spoke_width: float, semiangle_cutoff: float, energy: float = None):
        self._num_spokes = num_spokes
        self._spoke_width = spoke_width
        super().__init__(energy=energy, semiangle_cutoff=semiangle_cutoff)

    @property
    def num_spokes(self):
        return self._num_spokes

    @property
    def spoke_width(self):
        return self._spoke_width

    @property
    def metadata(self):
        metadata = {}
        return metadata

    def evaluate_with_alpha_and_phi(self, alpha: Union[float, np.ndarray], phi) -> Union[float, np.ndarray]:
        xp = get_array_module(alpha)
        alpha = xp.array(alpha)
        semiangle_cutoff = self.semiangle_cutoff / 1e3

        array = alpha < semiangle_cutoff
        array = array * (((phi + self.spoke_width / 2) * self.num_spokes) % (2 * np.pi) < (
                self.spoke_width * self.num_spokes))
        return array
```

We can use this aperture with our probe as below (or with any other probe method).

```
probe = abtem.Probe(sampling = 0.05, 
                extent = 30, 
                energy = 100e3, 
                aperture = MyAperture(4, np.pi / 4,  30),
                defocus = 50,
               )

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,6))
probe.build().intensity().show(ax=ax1)
probe.build().diffraction_patterns().show(ax=ax2);
```
![billede](https://user-images.githubusercontent.com/17334286/185920674-ec96bc06-b076-4bc5-8626-113cfdd2b111.png)

Note that the `abtem-dask` branch is not merged for a reason, so there could be issues. We have a rough version of the [docs](https://abtem.github.io/doc/user_guide/walkthrough/walkthrough.html) up for the branch, the walkthrough up to including "Frozen Phonons", should be reasonable.

**Comment by smribet** [comment] 2022-08-22 23:03
Thank you so much for making these changes and the detailed explanation! I started with some basic tests today and everything looks good. I will get back to you later in the week as I keep working on this.

**Comment by TomaSusi** [comment] 2023-04-21 07:11
@smribet presumably we can close this issue now?

**Comment by smribet** [comment] 2023-04-21 16:27
Yes, thank you!

**Comment by TomaSusi** [comment] 2023-04-25 06:36
@smribet ah one more thing: would you mind contributing a tutorial on using this new functionality? Just a Jupyter notebook with example code and some narrative would be enough, I can take care of unifying the formatting and adding it to the docs.

**Comment by smribet** [comment] 2023-04-27 01:24
Happy to! I will send something in the next few days.

**Comment by smribet** [comment] 2023-05-02 15:36
Apologies for the delay. Here are two notebooks - one for the main branch and the other for the dask.
[abtem examples.zip](https://github.com/abTEM/abTEM/files/11374999/abtem.examples.zip)

**Comment by TomaSusi** [comment] 2023-05-04 13:08
Why did you choose such a large sampling? I don't think that is a good idea, with your parameters just the regular probe without an aperture was showing artifacts away from spherical symmetry.

**Comment by TomaSusi** [comment] 2023-05-04 13:15
Hmm... it seems to really be necessary to create a new probe with the desired aperture, instead of modifying the aperture attribute of an existing probe. I guess this is because e.g. the bullseye aperture is a different class, @jacobjma?

**Comment by TomaSusi** [comment] 2023-05-04 14:16
Oh and another thing @smribet: for this tutorial, it would be good to have an example specimen and a multislice simulation that illustrates the effect of these probe modifications. Would you have something handy, or could you just suggest the type of simulation you think would be nice to demonstrate and I can generate one?

**Comment by smribet** [comment] 2023-05-09 16:21
Here are two quick examples: 
1. A STEM simulation with a bullseye amplitude plate, like the ones we use for disk detection
2. A TEM simulation with a phase plate to improve transfer of information 
[probe_mod_examples.zip](https://github.com/abTEM/abTEM/files/11433405/probe_mod_examples.zip)

**Comment by TomaSusi** [comment] 2023-05-11 08:01
Awesome, thanks! A couple of questions:

1. For the bullseye example, why show the two `measurement[0, 0]` and `measurement[0, 1]`, do these have some special meaning?
2. For the Zernike plate, it seems you probably were writing these examples before the new flexible aperture code was created. Shouldn't we add this as a separate class into the code itself, it seems to me Zernike phase plates are one of the most typical use cases?

**Comment by TomaSusi** [comment] 2023-05-12 08:16
Also, I am struggling to reproduce the Bullseye example with the newer `abtem.transfer.Bullseye()` code; as far as I understand, we're not supposed to set the CTF of the probe, but rather the aperture, and I can't get the kind of diffraction patterns your code example written for the old version of abTEM produces...

**Comment by smribet** [comment] 2023-05-12 22:30
1. The positions that I selected don't have any special meaning. Sorry for the confusion! 
2. yes the Zernike would be a good addition. 

What kind of errors were you seeing? I am attaching a notebook for the Nickel bullseye patterns with the dask branch. I am not very familiar with the dask branch, but it seems to be working for me. The biggest difference I see is that the dask bullseye has spokes. Perhaps I am missing something though - is this how things are looking on your end?

The examples I sent were for the main not dask branch. Where were you planning to add the examples? 

[bullseye_dask_with_Ni.ipynb.zip](https://github.com/abTEM/abTEM/files/11468112/bullseye_dask_with_Ni.ipynb.zip)

**Comment by TomaSusi** [comment] 2023-05-16 08:42
I'm not doing any further work on the soon-to-be-replaced master branch, so everything I say applies to Dask only. I wasn't seeing an error, but was just unable to reproduce the tidy bullseyes in your diffraction patterns – I'll have a look at the updated example!

**Comment by TomaSusi** [comment] 2023-05-16 08:52
Ah, now I realize what my biggest issue was – I forgot that the real-space extent of the potential determines the reciprocal-space sampling of the diffraction patterns, and had modified the model to be too small.

**Comment by TomaSusi** [comment] 2023-05-16 09:26
For the Zernike example, the cutoff parameter corresponds to the size of the "hole" in the plate in mrad (corresponding to e.g. https://www.jeol.com/words/emterms/20121023.002800.php#gsc.tab=0)?

**Comment by smribet** [comment] 2023-05-22 17:48
Yes exactly! Apologies, perhaps something like `center_hole_cutoff` would be better to help distinguish from the `semiangle_cutoff`.

**Closed** 2023-10-02 12:59 UTC
