### ISSUE TITLE
beam tilt not taking effect when using a simple tilt value

### ISSUE THREAD

**Issue by wdwzyyg** [abTEM/abTEM#151] opened 2024-04-23 19:05 UTC
I was trying to introduce beam tilt and struggled for a while since I didn't see any changes in my diffraction pattern with a tilted beam. Eventually I found that the argument tilt needs to be an abtem.distribution object as shown in the example (https://abtem.readthedocs.io/en/latest/user_guide/walkthrough/multislice.html?highlight=Small-angle%20beam%20tilt#small-angle-beam-tilt). If I just pass single values, tilt = (a, b), it does not work. 

It's still quite easy and usable but just a little confusing at the beginning, so I'd like to post here as a quick note to other users. 
![image](https://github.com/abTEM/abTEM/assets/54558463/aa4361af-b077-419d-885e-959e3de30034)

**Comment by jacobjma** [comment] 2024-04-29 11:43
Thank you very much for the report! I can reproduce the issue, it should be fixed soon.

**Comment by jacobjma** [comment] 2024-05-13 20:33
I am sorry. I actually can't reproduce your issue can you provide the code to reproduce your issue. What is the potential? It seems to me that it is just a zero potential. There is an issue with the

**Comment by jacobjma** [comment] 2024-05-20 13:55
This is now solved in the main branch, it will fixed in the next release. Thank you for finding the issue.

**Closed by jacobjma** 2024-05-20 13:55 UTC
