### ISSUE TITLE
Prism phase aberration part, axis metadata error

### ISSUE THREAD

**Issue by qiuzanlin** [abTEM/abTEM#152] opened 2024-05-01 05:31 UTC
I face some problem in Prism with phase aberration part. 

Here are my code. 

defocus = -np.linspace(0, 80, 5)

ctf = abtem.CTF(defocus=defocus)

detector = abtem.AnnularDetector(inner=80, outer=250)

scan = abtem.GridScan(sampling=0.2)

measurement_with_aberrations = s_matrix_interpolated.scan(
    scan=scan, detectors=detector, ctf=ctf
).compute()

measurement_with_aberrations =  measurement_with_aberrations.interpolate(0.1).gaussian_filter(0.3).compute()

measurement_with_aberrations.show(
    explode=True,
    figsize=(10, 6),
);

When running the code, I receive the error and it shows. 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 1
----> 1 measurement_with_aberrations =  measurement_with_aberrations.interpolate(0.1).compute()
      3 measurement_with_aberrations.show(
      4     explode=True,
      5     figsize=(10, 6),
      6 );

File E:\envs\abtem\lib\site-packages\abtem\measurements.py:1447, in Images.interpolate(self, sampling, gpts, method, boundary, order, normalization, cval)
   1445 kwargs["sampling"] = sampling
   1446 kwargs["array"] = array
-> 1447 return self.__class__(**kwargs)

File E:\envs\abtem\lib\site-packages\abtem\measurements.py:1149, in Images.__init__(self, array, sampling, ensemble_axes_metadata, metadata)
   1145     sampling = float(sampling[0]), float(sampling[1])
   1147 self._sampling = sampling
-> 1149 super().__init__(
   1150     array=array,
   1151     ensemble_axes_metadata=ensemble_axes_metadata,
   1152     metadata=metadata,
   1153 )

File E:\envs\abtem\lib\site-packages\abtem\measurements.py:342, in BaseMeasurements.__init__(self, array, ensemble_axes_metadata, metadata)
    336 def __init__(
    337     self,
    338     array: np.ndarray | da.core.Array,
    339     ensemble_axes_metadata: list[AxisMetadata],
    340     metadata: dict,
    341 ):
--> 342     super().__init__(
    343         array=array,
    344         ensemble_axes_metadata=ensemble_axes_metadata,
    345         metadata=metadata,
    346     )

File E:\envs\abtem\lib\site-packages\abtem\array.py:318, in ArrayObject.__init__(self, array, ensemble_axes_metadata, metadata)
    312 if len(array.shape) < self._base_dims:
    313     raise RuntimeError(
    314         f"{self.__class__.__name__} must be {self._base_dims}D or greater, not "
    315         f"{len(array.shape)}D"
    316     )
--> 318 self._check_axes_metadata()

File E:\envs\abtem\lib\site-packages\abtem\array.py:363, in ArrayObject._check_axes_metadata(self)
    361 def _check_axes_metadata(self):
    362     if len(self.shape) != len(self.axes_metadata):
--> 363         raise RuntimeError(
    364             f"number of array dimensions ({len(self.shape)}) does not match number of axis metadata items "
    365             f"({len(self.axes_metadata)})"
    366         )
    368     for n, axis in zip(self.shape, self.axes_metadata):
    369         if isinstance(axis, OrdinalAxis) and len(axis) != n:

RuntimeError: number of array dimensions (3) does not match number of axis metadata items (2)

I think this error might have something to do with the axis metadata, which not match with the array dimensions. 

So, I decrease the number of defocus array from 5 to 1 and it works. But it is quite inconvenience for running more aberration. 

Hope this bug can be fixed. 

By the way, I use gpu device for calculation so I am not sure if this is a bug for gpu calculation.

**Comment by jacobjma** [comment] 2024-05-03 20:14
Thank you. It should be fixed now (in the main branch). I am not sure though because, your message is not very descriptive.

Next time try to provide enough code, such that I can reproduce your error. 

I still appreciate the report.

**Comment by qiuzanlin** [comment] 2024-05-04 11:27
Yes, the main branch is fixed. Thanks for the help.

**Comment by jacobjma** [comment] 2024-05-06 14:18
Thank very much you @qiuzanlin again👍. If you find any other issues please raise them. I will close this issue

**Closed by jacobjma** 2024-05-06 14:18 UTC
