### ISSUE TITLE
Bug in pyfftw.pyfftw.FFTW.__cinit__ when using high performance computer

### ISSUE THREAD

**Issue by Monarch-Azir** [abTEM/abTEM#127] opened 2023-11-09 11:01 UTC
Hi abTEM developer,

Recently, I simulated the HRTEM image using my laptop, there is no problem with the code. Then I run the same code using the high performance computer provided by the university, but this time, an error occurred:

`
Traceback (most recent call last):
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 99, in get_fftw_object
    fftw = pyfftw.FFTW(
  File "pyfftw/pyfftw.pyx", line 1424, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: No FFTW wisdom is known for this plan.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc/puhome/______/test/Frankenstein.py", line 197, in <module>
    measurement_ensemble = exit_wave.apply_ctf(ctf)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/waves.py", line 898, in apply_ctf
    return self.apply_transform(ctf, max_batch=max_batch)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/array.py", line 1271, in apply_transform
    return transform.apply(self)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/transform.py", line 365, in apply
    waves = super().apply(waves)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/transform.py", line 311, in apply
    new_array = self._calculate_new_array(array_object)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/transform.py", line 642, in _calculate_new_array
    new_array = ifft2(new_array, overwrite_x=self.in_place)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 178, in ifft2
    return _fft_dispatch(x, func_name="ifft2", overwrite_x=overwrite_x, **kwargs)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 152, in _fft_dispatch
    return _fftw_dispatch(x, func_name, overwrite_x, **kwargs)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 142, in _fftw_dispatch
    return get_fftw_object(x, func_name, overwrite_x=overwrite_x, **kwargs)()
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 118, in get_fftw_object
    _new_fftw_object(array, name, flags=flags)
  File "/puhome/______/.local/lib/python3.10/site-packages/abtem/core/fft.py", line 49, in _new_fftw_object
    fftw_object = pyfftw.FFTW(
  File "pyfftw/pyfftw.pyx", line 1426, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
`

Since this code can be performed without the error using my laptop and other ordinary computers, I think this is a bug. And the error message also indicates that.

Hope you can fix this problem or help to avoid it.

**Comment by jacobjma** [comment] 2023-11-09 19:06
I can't reproduce this problem, so it is difficult to solve. It seems to be related to pyFFTW. Could you check that pyFFTW works outside of abTEM? Or else please provide the code that fails.

A workaround would be using MKL instead of FFTW; this can even be slightly faster. You can select `MKL` instead of `FFTW` by writing the following at the beginning of your document:
```
abtem.config.set({"fft": "mkl"})
```
You need to have `mkl_fft` installed:

```
conda install -c conda-forge mkl_fft
```

**Comment by jacobjma** [comment] 2023-11-11 11:00
I looked into this a little more and can now reproduce it, but only on Linux and installing through Conda. It seems to be a [known issue](https://github.com/pyFFTW/pyFFTW/issues/294) in pyFFTW.  I was able to fix it by just overwriting the pyFFTW installation with the version from pip:
```
pip install pyfftw --force-reinstall --no-deps 
```
It seems that the issue might be close to being fixed with this [this PR](https://github.com/pyFFTW/pyFFTW/pull/363); it only needs a final review.

**Comment by SK001-E** [comment] 2023-11-14 15:57
I was having the same problem, and the above fix worked. Thanks.

**Comment by rfwebster** [comment] 2023-11-15 06:52
same for me on ubuntu and python 3.11 - thanks!

**Closed** 2023-12-14 09:28 UTC

**Comment by argerlt** [comment] 2025-05-12 21:49
Adding to this since I just lost a day to the same problem. Computer specs below:

> Ubuntu 24.04 on Dell Precision
> Intel i7-14700K
> RTX 4070

@tpchuckles solution didn't work for me, but got me on the right track. The following was fast and worked for my machine:
- Fully delete conda envrionment
- apt-install `gcc` and `gfortran`
-  [download fftw3](http://www.fftw.org/fftw2_doc/fftw_6.html) and build using default settings 
- Create a new environment and conda install `abtem` normally

Also, as per the suggestion by @jacobjma 

> A workaround would be using MKL instead of FFTW; this can even be slightly faster. 

Others milage may vary, but for my test simulation in `abtem1.0.6`,  `mkl` was almost twice as fast, and `cupy` nearly 6 times as fast as `pyfftw`
